<a href="https://colab.research.google.com/github/edr1/ProgrammingAssignment2/blob/master/AtividadePrevia_VCD_CIFAR_10_ERICK_DELGADO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from __future__ import print_function
from PIL import Image
import requests
from io import BytesIO
import numpy as np
from keras.callbacks import EarlyStopping
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Flatten
from keras.layers.convolutional import Conv2D
from keras.optimizers import Adam
from keras.layers.pooling import MaxPooling2D
from keras.utils import to_categorical

Using TensorFlow backend.


In [3]:
np.random.seed(1000)
(X_train, Y_train), (X_test, Y_test) = cifar10.load_data()

# Create the model and add layers: 
#- Uma camada convolucional;
#- Uma camada de max pooling;
#- Uma camada convolucional;
#- Uma camada de max pooling;
#- Uma camada de dropout;
#- Transformamos os mapas de características em um único vetor;
#- Uma camada totalmente conectada;
#- Uma camada de dropout;
#- Uma camada totalmente conectada.
model = Sequential()

model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(32, 32, 3)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(1024, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))


Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [4]:
# Executar o nosso modelo
model.compile(loss='categorical_crossentropy',
              optimizer=Adam(lr=0.0001, decay=1e-6),
              metrics=['accuracy'])
# Realiza o treinamento 		  
model.fit(X_train / 255.0, to_categorical(Y_train),
          batch_size=128,
          shuffle=True,
          epochs=10,
          validation_data=(X_test / 255.0, to_categorical(Y_test)))
# Realiza o teste
scores = model.evaluate(X_test / 255.0, to_categorical(Y_test))
# Printar valor de erro e accuracia obtida
print('Loss: %.3f' % scores[0])
print('Accuracy: %.3f' % scores[1])

Instructions for updating:
Use tf.cast instead.
Train on 50000 samples, validate on 10000 samples
Epoch 1/10
50000/50000 [==============================] - 9s 178us/step - loss: 1.8709 - acc: 0.3251 - val_loss: 1.5727 - val_acc: 0.4512
Epoch 2/10
50000/50000 [==============================] - 7s 138us/step - loss: 1.5284 - acc: 0.4533 - val_loss: 1.4047 - val_acc: 0.5145
Epoch 3/10
50000/50000 [==============================] - 7s 139us/step - loss: 1.4079 - acc: 0.5029 - val_loss: 1.3336 - val_acc: 0.5357
Epoch 4/10
50000/50000 [==============================] - 7s 140us/step - loss: 1.3302 - acc: 0.5317 - val_loss: 1.2549 - val_acc: 0.5576
Epoch 5/10
50000/50000 [==============================] - 7s 140us/step - loss: 1.2758 - acc: 0.5520 - val_loss: 1.2206 - val_acc: 0.5708
Epoch 6/10
50000/50000 [==============================] - 7s 140us/step - loss: 1.2333 - acc: 0.5669 - val_loss: 1.1796 - val_acc: 0.5874
Epoch 7/10
50000/50000 [==============================] - 7s 138us/step - 

In [5]:
# Testar o modelo obtido
response = requests.get('https://dl1.cbsistatic.com/i/r/2017/02/01/4094f803-44d1-47e0-a22f-6d48f65727b5/thumbnail/32x32/4188676421c43926bfcb5f3329ffacb6/fmimg586302198861076950.png')
img = Image.open(BytesIO(response.content))
img = np.expand_dims(img, axis=0)
img = img[:,:,:,:3]

print(model.predict(img))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:
# Testando com um objeto Carro 1
response = requests.get('https://www.finderr.de/icon/steinacker-automobile.de-favicon.png')
img = Image.open(BytesIO(response.content))
img = np.expand_dims(img, axis=0)
img = img[:,:,:,:3]

print(model.predict(img))


[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
# Testando com um objeto Carro 2
response = requests.get('https://dl1.cbsistatic.com/i/r/2017/02/01/ca33832c-72c3-4ada-8044-5f7380f30dcf/thumbnail/32x32/2296f3ab912760b96b3ae3b59328b2da/fmimg8676746949770611684.png')
img = Image.open(BytesIO(response.content))
img = np.expand_dims(img, axis=0)
img = img[:,:,:,:3]
print(model.predict(img))


[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [8]:
# Testando com um objeto Passaro 1
response = requests.get('https://dl1.cbsistatic.com/i/r/2017/02/01/ad9af602-f66d-4eb6-891b-e42f90bb3b62/thumbnail/32x32/664c4f638e58cb033ea96a4978ca9b77/fmimg6566880612367031360.png')
img = Image.open(BytesIO(response.content))
img = np.expand_dims(img, axis=0)
img = img[:,:,:,:3]
print(model.predict(img))

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


In [9]:
# Testando com um objeto Cachorro 1
response = requests.get('http://www.icons101.com/icon_png/size_32/id_71981/dog.png')
img = Image.open(BytesIO(response.content))
img = np.expand_dims(img, axis=0)
img = img[:,:,:,:3]
print(model.predict(img))


[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.0000000e+00 0.0000000e+00 0.0000000e+00 2.7315852e-09 0.0000000e+00]]


In [10]:
# Testando com um objeto Caminhão 1
response = requests.get('https://dl1.cbsistatic.com/i/r/2017/02/01/7d981122-b060-42a2-bf6a-2f79ff0f1338/thumbnail/32x32/354f2635f4f597ad62cf9574264712e6/fmimg5476972265364039413.png')
img = Image.open(BytesIO(response.content))
img = np.expand_dims(img, axis=0)
img = img[:,:,:,:3]
print(model.predict(img))



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
